version: "3.9"

services:
  db:
    image: postgres
    container_name: db
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      timeout: 25s
      interval: 5s
      retries: 5
    restart: always
    ports:
      - "5000:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: test
    volumes:
      - ./backend/db_init/01-init.sh:/docker-entrypoint-initdb.d/01-init.sh

  fastapi-app:
    build:
      context: ./backend
      args:
        db_host: db
        db_port: 5432
        db_username: postgres
        db_password: 123456
        db_name: test
    image: fastapi-app
    container_name: fastapi-app
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 5001:8000
    depends_on:
      - db

  react-app:
    build:
      context:
        ./frontend
    image: react-app
    container_name: react-app
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 5002:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - fastapi-app

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 3000:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - react-app