version: "3.9"

services:
  db:
    image: postgres
    container_name: db
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      timeout: 25s
      interval: 5s
      retries: 5
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ISSAP
    volumes:
      - ./backend/db_init/01-init.sh:/docker-entrypoint-initdb.d/01-init.sh

  fastapi-app:
    build:
      context: ./backend
      dockerfile: Dockerfile-product
    image: fastapi-app
    container_name: fastapi-app
    environment:
      - DB=postgresql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - DB_NAME=ISSAP
      - API_ROOT_PATH=/api
    depends_on:
      - db

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile-product
    image: react-app
    container_name: react-app
    depends_on:
      - fastapi-app
    ports:
      - 80:80
